INSERT INTO CURRENCY_EXCHANGE  (id,CURRENCY_FROM,CURRENCY_TO,conversion_multiple,environment)
VALUES (1001,'USD','INR',65,'');
INSERT INTO CURRENCY_EXCHANGE  (id,CURRENCY_FROM,CURRENCY_TO,conversion_multiple,environment)
VALUES (1002,'MAD','INR',75,'');
INSERT INTO CURRENCY_EXCHANGE  (id,CURRENCY_FROM,CURRENCY_TO,conversion_multiple,environment)
VALUES (1003,'EUR','INR',25,'');